---
title: "salary_2022_analysis"
author: "Victoria Stavish"
date: "2022-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libraries

```{r cars}

library(tidyverse)
library(janitor)
library(lubridate)
library(dplyr)
library(readxl)
library(ggplot2)

```

# load data

```{r}

salary_2022 <- read_xlsx("salary_2022.xlsx")

```

# create dataframe of only non-tenured faculty
# there are 3,343 non-tenured faculty

```{r}

non_tenured <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Non-Tenured", category_status))

non_tenured_sum <- non_tenured %>%
  summarise(
    appt_base_annual_salary = sum(appt_base_annual_salary, na.rm=TRUE)
  )

avg_non_tenured <- non_tenured_sum /3343

```

# tenured
# there are 1,353 tenured faculty

```{r}
tenured <- salary_2022 %>%
as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty", category_status))

tenured_sum <- tenured %>%
  summarise(
    appt_base_annual_salary = sum(appt_base_annual_salary, na.rm=TRUE)
  )

avg_tenured <- tenured_sum /1353


```

# tenure and non-tenure faculty by division

```{r}

by_division <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  select(division, category_status, appt_base_annual_salary) %>%
  filter(grepl("Tenured | Tenure | Non", category_status)) %>%
  group_by(division, category_status) %>%
  count(category_status)

```

# how many faculty in each division?

```{r}
division_faculty <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  group_by(division) %>%
  count(division) %>%
  arrange(desc(n))

```

# avg tenure and non-tenure salary by division

```{r}

engineering <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "A. James Clark School of Engineering") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

cmns <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Computer, Math & Natural Sciences") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

pres <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "Office of the President") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

agr <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Agriculture & Natural Resources") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

arhu <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "	
College of Arts & Humanities") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

bsos <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Behavioral & Social Sciences") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

education <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Education") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

infosci <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Information Studies") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

jour <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "Philip Merrill College of Journalism") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

business <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "Robert H. Smith School of Business") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

architecture <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "School of Architecture, Planning, & Preservation") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

sph <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "School of Public Health") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

policy <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "School of Public Policy") %>%
  group_by(category_status_cd, category_status) %>%
  count(category_status_cd)

```

# avg salary by division


```{r}

salengineering <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "A. James Clark School of Engineering") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )
  

salcmns <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Computer, Math & Natural Sciences") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

salpres <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "Office of the President") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

salagr <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Agriculture & Natural Resources") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

salarhu <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "	
College of Arts & Humanities") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

salbsos <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Behavioral & Social Sciences") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

saleducation <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Education") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

salinfosci <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Information Studies") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

saljour <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "Philip Merrill College of Journalism") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

salbusiness <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "Robert H. Smith School of Business") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

salarchitecture <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "School of Architecture, Planning, & Preservation") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

salsph <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "School of Public Health") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

salpolicy <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "School of Public Policy") %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

```

# tenure faculty salary by division

```{r}

nonengineering <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "A. James Clark School of Engineering") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )
  

noncmns <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Computer, Math & Natural Sciences") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

nonpres <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "Office of the President")%>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

nonagr <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Agriculture & Natural Resources") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

nonarhu <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Arts & Humanities") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

nonbsos <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Behavioral & Social Sciences") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

noneducation <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Education") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

noninfosci <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "College of Information Studies") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

nonjour <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "Philip Merrill College of Journalism") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

nonbusiness <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "Robert H. Smith School of Business") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

nonarchitecture <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "School of Architecture, Planning, & Preservation") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

nonsph <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "School of Public Health") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

nonpolicy <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(division == "School of Public Policy") %>%
  filter(category_status_cd %in%  c("15", "03", "37")) %>%
  mutate(appt_base_annual_salary = as.numeric(appt_base_annual_salary)) %>%
  summarise(
    appt_base_annual_salary = median(appt_base_annual_salary, na.rm=TRUE)
  )

```



# duplicate names

```{r}

duplicate_names <- salary_2022 %>%
  as.data.frame() %>%
  clean_names() %>%
  group_by(category_status_cd, primary_name) %>%
  count(primary_name) %>%
  filter(n>1)



```






