---
title: "Grocery Store Analysis"
author: "Shreya Vuttaluru"
date: '2022-11-01'
output: html_document
---

```{r setup, include=FALSE}
## general packages
library(tidyverse)
library(tidycensus)
library(shiny)
library(shinythemes)
library(shinyWidgets)
library(janitor)
library(lubridate)
library(leaflet)
library(leaflet.extras)
library(shiny)
library(readxl)

## geocoding packages
library(ggmap)
library(tmaptools)
library(RCurl)
library(jsonlite)
library(tidyverse)
library(leaflet)
library(sf)

## census API
census_api_key("82c33dd2db316b78367d3476bcb90d2abe65a69a", install = TRUE, overwrite = TRUE)


```

## Load Grocery Store Data
```{r}

#full dataset
historic_snap <- read_csv("snap_data.csv") %>%
  clean_names()

## filter for md
md_snap <- historic_snap %>%
  filter(state == "MD")

### FARA data -- this dataset already filters out convenience stores and uses USDA metrics for food deserts
fara_data <- read_excel("FARA_2019.xlsx", sheet = "Food Access Research Atlas")

clean_fara_data <- fara_data %>%
  clean_names() %>%
  filter(county == "Prince George's County")


```


### Get Census Vars by Tract

```{r}

### decennial census variables 
decennial_vars <- load_variables(2020, dataset="pl")

### pull 2021 ACS data 
race_2020 <- get_decennial(
  geography = "tract", 
  state = "MD",
  variables = 
    c(total_population = "P2_001N",
      white_pop = "P2_005N",
      black_pop = "P2_006N",
      hisp_lat_pop = "P2_002N",
      asian_pop = "P2_008N"),
  year = 2020,
  geometry = TRUE,
  output = "wide"
  ) %>% 
  mutate(year=("2020")) %>%
  clean_names() %>%
  separate(name, into=c("tract","name","state"), sep=",") %>%
  mutate(
      state = str_trim(state,side="both"),
      name = str_trim(name,side="both")
  )

### save 2020 census vars as RDS so we don't have to pull every time
write_rds(race_2020, "census_data.rds")

race_percentages <- race_2020 %>%
  mutate(
    percent_white = round((white_pop/total_population) * 100, 2),
    percent_black = round((black_pop/total_population) * 100, 2),
    percent_hisp_lat = round((hisp_lat_pop/total_population) * 100, 2),
    percent_asian = round((asian_pop/total_population) * 100, 2) 
    ) %>%
  dplyr::select(geoid, tract, name, state, percent_white, percent_black, percent_hisp_lat, percent_asian, total_population)

### prince goerge's county relavent stats
pg_demos <- race_percentages %>%
  filter(name == "Prince George's County")


#### ACS Data for 2019 
acs_2019 <- get_acs(
  geography = "tract", 
  state = "MD",
  variables = 
    c(total_population = "B03002_001",
      white_pop = "B03002_003",
      black_pop = "B03002_004",
      hisp_lat_pop = "B03002_012",
      asian_pop = "B03002_006"),
  year = 2019,
  geometry = TRUE,
  output = "wide"
  ) %>% 
  mutate(year=("2019")) %>%
  clean_names() %>%
  separate(name, into=c("tract","name","state"), sep=",") %>%
  mutate(
      state = str_trim(state,side="both"),
      name = str_trim(name,side="both")
  )

acs_percentages <- acs_2019 %>%
  mutate(
    percent_white = round((white_pop_e/total_population_e) * 100, 2),
    percent_black = round((black_pop_e/total_population_e) * 100, 2),
    percent_hisp_lat = round((hisp_lat_pop_e/total_population_e) * 100, 2),
    percent_asian = round((asian_pop_e/total_population_e) * 100, 2) 
    ) %>%
  dplyr::select(geoid, tract, name, state, percent_white, percent_black, percent_hisp_lat, percent_asian, total_population_e)

### prince goerge's county relavent stats
acs_pg_demos <- acs_percentages %>%
  filter(name == "Prince George's County")

```

### Joins
```{r}

### Spatial join pg county demographics to SNAP

## wgs projection
wgs <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"

## make snap into sf object, make sure crs is consistent
spatial_snap <- st_as_sf(historic_snap,
                        crs = wgs,
                        coords = c("longitude", "latitude")
)

spatial_pg_demos <- st_transform(pg_demos, crs = wgs)

##join
census_grocery_join <- spatial_pg_demos %>%
  st_join(spatial_snap)


### JOIN FARA data 
fara_with_demos <- clean_fara_data %>%
  left_join(acs_pg_demos, by=c("census_tract"="geoid"))



```

### Looking really quickly at stores in neighborhoods that are Black
```{r}

## For now, let's filter out convenience stores:
no_convenience <- census_grocery_join %>%
  filter(store_type != "Convenience Store") %>%
  st_drop_geometry()

## how many grocery stores are there in neighborhoods that are majority black versus neighborhoods that aren't 

majority_black_tracts <- no_convenience %>%
  mutate(
    majority_black_y_n = case_when(percent_black >= 50 ~ "Y",
                                   percent_black < 50 ~ "N")
  ) %>%
  group_by(majority_black_y_n) %>%
  summarize(
    count = n()
  ) 

```

### FARA Analysis -- looking at 1/2 mile access for urban area
```{r}

### urban tracts
urban_fara <- fara_with_demos %>%
  filter(urban == "1")
### most tracts in P.G. county are considered urban

### LILA at 1/2 miles
access_one_mile <- fara_with_demos %>%
  filter(lila_tracts_1and10 == "1")
### 98/218 census tracts in Prince George's County don't have access to a grocery store within 1/2 a mile

### some demos 
black_half_mile <- access_half_mile %>%
  dplyr::select(census_tract, state.x, percent_black, percent_hisp_lat, total_population_e, geometry) %>%
  filter(percent_black > 50)

hisp_half_mile <- access_half_mile %>%
  dplyr::select(census_tract, state.x, percent_black, percent_hisp_lat, total_population_e, geometry) %>%
  filter(percent_hisp_lat > 50)
  

access_half_mile <- fara_with_demos %>%
  filter(lila_tracts_half_and10 == "1")
### 25/218 census tracts in Prince George's County don't have access to a grocery store within 1/2 a mile



```
