---
title: "Legder Data -- Maryland Correctional Enterprises"
by: Shreya Vuttaluru
output: html_notebook
---

```{r}

library(tidyverse)
#install.packages("dplyr")
library(janitor)
library(lubridate)
#install.packages("censusxy")
library(censusxy)
library(dplyr)
library(parallel)
library(tictoc)
library(furrr)
library(leaflet)
library(leaflet.extras)
library(sf)
#install.packages("sp")
library(sp)
#install.packages("readxl")
library(readxl)
library(data.table)
library(jsonlite)
library(geojsonsf)
library(geojsonio)
#install.packages(c("rgdal", "tidycensus"))
library(tidycensus)
#install.packages("fuzzyjoin")
library(fuzzyjoin)
#install.packages("stringdist")
library(stringdist)
#install.packages("rmapzen")
library(rmapzen)
#install.packages("writexl")
library(writexl)
library(rgdal)
#install.packages("spatialEco")
library(spatialEco)
#install.packages("raster")
library(raster)
library(dplyr)

```

Reading in data
```{r}

ledger_2017 <- read_excel("ledger_data/2017.xls")
ledger_2018 <- read_excel("ledger_data/2018.xls")
ledger_2019 <- read_excel("ledger_data/2019.xls")
ledger_2020 <- read_excel("ledger_data/2020.xls")
ledger_2021 <- read_excel("ledger_data/2021.xlsx")
ledger_2022 <- read_excel("ledger_data/2022.xls")

```

Analysis!
```{r}
### Filtering for Maryland correctional enterprises in each year
correctional_spending_2017 <- ledger_2017 %>%
  clean_names %>%
  filter(vendor_name == "MARYLAND CORRECTIONAL")

correctional_spending_2017 %>%
  summarize(
    sum(grand_total_amt)
  )

correctional_spending_2018 <- ledger_2018 %>%
  clean_names %>%
  filter(vendor_name == "MARYLAND CORRECTIONAL")

correctional_spending_2018 %>%
  summarize(
    sum(grand_total_amt)
  )

correctional_spending_2019 <- ledger_2019 %>%
  clean_names %>%
  filter(vendor_name == "MARYLAND CORRECTIONAL")

correctional_spending_2019 %>%
  summarize(
    sum(grand_total_amt)
  )

correctional_spending_2020 <- ledger_2020 %>%
  clean_names %>%
  filter(vendor_name == "MARYLAND CORRECTIONAL")

correctional_spending_2020 %>%
  summarize(
    sum(grand_total_amt)
  )

correctional_spending_2021 <- ledger_2021 %>%
  clean_names %>%
  filter(vendor_name == "MARYLAND CORRECTIONAL")

correctional_spending_2021 %>%
  summarize(
    sum(amt_paid)
  )

correctional_spending_2022 <- ledger_2022 %>%
  clean_names %>%
  filter(vendor_name == "MARYLAND CORRECTIONAL")

correctional_spending_2022 %>%
  summarize(
    sum(grand_total_amt)
  )

```
#finding most common depts 2021-2022

```{r}
depts_2021 <- correctional_spending_2021 %>%
  group_by(organization_name) %>%
  tally() %>%
  mutate(percent = (n / sum(n) * 100)) %>%
  arrange(desc(percent))

depts_2022 <- correctional_spending_2022 %>%
  group_by(organization_name) %>%
  tally() %>%
  mutate(percent = (n / sum(n) * 100)) %>%
  arrange(desc(percent))

# now looking at most common depts orders overall 2021

res_facilities2021 <- correctional_spending_2021 %>%
  filter(organization_name == "VPSA-Res Facilities-Admin Svcs")

vp_2021 <- correctional_spending_2021 %>%
  filter(organization_name == "SVPAAP-Sr VP Academic Affairs & Provost")

tech_2021 <- correctional_spending_2021 %>%
  filter(organization_name == "VPA-FM-P&C-Technical Support")

# most commons depts orders overall 2022

cmns_2022 <- correctional_spending_2022 %>%
  filter(organization_name == "CMNS-Chemistry & Biochemistry")

sphl_2022 <- correctional_spending_2022 %>%
  filter(organization_name == "SPHL-School of Public Health")

  
```
#Finding most common order titles

```{r}
items_2017 <- correctional_spending_2017 %>%
  group_by(item_ld) %>%
  tally() %>%
  mutate(percent = (n / sum(n) * 100)) %>%
  arrange(desc(percent))

items_2018 <- correctional_spending_2018 %>%
  group_by(item_ld) %>%
  tally() %>%
  mutate(percent = (n / sum(n) * 100)) %>%
  arrange(desc(percent))

items_2019 <- correctional_spending_2019 %>%
  group_by(item_ld) %>%
  tally() %>%
  mutate(percent = (n / sum(n) * 100)) %>%
  arrange(desc(percent))

items_2020 <- correctional_spending_2020 %>%
  group_by(item_ld) %>%
  tally() %>%
  mutate(percent = (n / sum(n) * 100)) %>%
  arrange(desc(percent))

items_2021 <- correctional_spending_2021 %>%
  group_by(itm_desc) %>%
  tally() %>%
  mutate(percent = (n / sum(n) * 100)) %>%
  arrange(desc(percent))

items_2022 <- correctional_spending_2022 %>%
  group_by(item_ld) %>%
  tally() %>%
  mutate(percent = (n / sum(n) * 100)) %>%
  arrange(desc(percent))
  
```
# football spending
```{r}
# 22 spending descending
football_spending22 <- ledger_2022 %>%
  clean_names %>%
  filter(organization_name == "PRES-ICA-Football")%>%
  arrange(desc(grand_total_amt))

# total amt spent
football22_sum <-ledger_2022 %>%
  clean_names %>%
  summarize(
    sum(grand_total_amt)
  )

# 21 is wack
football_spending21 <- ledger_2021 %>%
  clean_names %>%
  filter(organization_name == "PRES-ICA-Director's Office/Admin")%>%
  arrange(desc(amt_paid))

```

#basketball spending (mens)
```{r}
#22 spending
mbbal_spending22 <- ledger_2022 %>%
  clean_names %>%
  filter(organization_name == "PRES-ICA-Men's Basketball")%>%
  arrange(desc(grand_total_amt))


# total amt spent
mbbal22_sum <-ledger_2022 %>%
  clean_names %>%
  summarize(
    sum(grand_total_amt)
  )

```
# womens sports question mark
```{r}
wsports_22 <- ledger_2022 %>%
  clean_names %>%
  filter(organization_name == "PRES-ICA-Women's Sports")%>%
  arrange(desc(grand_total_amt))

# total amt spent
wsports22_sum <-ledger_2022 %>%
  clean_names %>%
  summarize(
    sum(grand_total_amt)
  )


```
# other mens sports
```{r}
mensports_22 <- ledger_2022 %>%
clean_names %>%
  filter(organization_name == "PRES-ICA-Other Men's Sports")%>%
  arrange(desc(grand_total_amt))

# total amt spent
mensports22_sum <-ledger_2022 %>%
  clean_names %>%
  summarize(
    sum(grand_total_amt)
  )

(football22_sum - wsports22_sum)

```